// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLessonAttendance = `-- name: GetLessonAttendance :many
SELECT DISTINCT
    s.id AS student_id,
    s.first_name,
    s.last_name,
    s.status,
    a.is_present,
    a.notes
FROM lessons l
LEFT JOIN student_groups sg
    ON sg.group_id = l.group_id
    AND sg.joined_at::date <= l.date
    AND (sg.left_at IS NULL OR sg.left_at::date > l.date)
JOIN students s
    ON (l.student_id = s.id OR sg.student_id = s.id)
LEFT JOIN attendance a
    ON a.lesson_id = l.id AND a.student_id = s.id
WHERE l.id = $1
ORDER BY s.last_name, s.first_name
`

type GetLessonAttendanceRow struct {
	StudentID pgtype.UUID      `json:"student_id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Status    NullEntityStatus `json:"status"`
	IsPresent pgtype.Bool      `json:"is_present"`
	Notes     pgtype.Text      `json:"notes"`
}

func (q *Queries) GetLessonAttendance(ctx context.Context, id pgtype.UUID) ([]GetLessonAttendanceRow, error) {
	rows, err := q.db.Query(ctx, getLessonAttendance, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonAttendanceRow
	for rows.Next() {
		var i GetLessonAttendanceRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.IsPresent,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendance = `-- name: UpsertAttendance :exec
INSERT INTO attendance (lesson_id, student_id, is_present, notes)
SELECT
    $1::uuid,
    unnest($2::uuid[]),
    unnest($3::boolean[]),
    unnest($4::text[])
ON CONFLICT (lesson_id, student_id)
DO UPDATE SET
    is_present = EXCLUDED.is_present,
    notes = EXCLUDED.notes
`

type UpsertAttendanceParams struct {
	Column1 pgtype.UUID   `json:"column_1"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 []bool        `json:"column_3"`
	Column4 []string      `json:"column_4"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error {
	_, err := q.db.Exec(ctx, upsertAttendance,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
