// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (name, address, city, status)
VALUES ($1, $2, $3, 'ACTIVE')
RETURNING id
`

type CreateBranchParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.Address, arg.City)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
