// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (name, address, city, status)
VALUES ($1, $2, $3, 'ACTIVE')
RETURNING id
`

type CreateBranchParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	City    string `json:"city"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.Address, arg.City)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllBranches = `-- name: GetAllBranches :many
SELECT id, name, address, city, status, created_at, updated_at
FROM branches
`

func (q *Queries) GetAllBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, getAllBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, name, address, city, status, created_at, updated_at
FROM branches
WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id pgtype.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchesByUserID = `-- name: GetBranchesByUserID :many
SELECT b.id, b.name, b.address, b.city, b.status, b.created_at, b.updated_at
FROM branches b
JOIN user_branches ub ON b.id = ub.branch_id
WHERE ub.user_id = $1
`

func (q *Queries) GetBranchesByUserID(ctx context.Context, userID pgtype.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, getBranchesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :exec
UPDATE branches
SET name = $1, address = $2, city = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateBranchParams struct {
	Name    string      `json:"name"`
	Address string      `json:"address"`
	City    string      `json:"city"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) error {
	_, err := q.db.Exec(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.City,
		arg.ID,
	)
	return err
}

const updateBranchStatus = `-- name: UpdateBranchStatus :exec
UPDATE branches
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateBranchStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) error {
	_, err := q.db.Exec(ctx, updateBranchStatus, arg.Status, arg.ID)
	return err
}
