// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package postgres

import (
	"context"
)

// iteratorForBulkCreateLessons implements pgx.CopyFromSource.
type iteratorForBulkCreateLessons struct {
	rows                 []BulkCreateLessonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateLessons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateLessons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BranchID,
		r.rows[0].TemplateID,
		r.rows[0].TeacherID,
		r.rows[0].SubjectID,
		r.rows[0].StudentID,
		r.rows[0].GroupID,
		r.rows[0].Date,
		r.rows[0].StartTime,
		r.rows[0].EndTime,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForBulkCreateLessons) Err() error {
	return nil
}

func (q *Queries) BulkCreateLessons(ctx context.Context, arg []BulkCreateLessonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lessons"}, []string{"branch_id", "template_id", "teacher_id", "subject_id", "student_id", "group_id", "date", "start_time", "end_time", "status"}, &iteratorForBulkCreateLessons{rows: arg})
}
