// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStudentToGroup = `-- name: AddStudentToGroup :exec
INSERT INTO student_groups (student_id, group_id, joined_at)
VALUES ($1, $2, $3)
`

type AddStudentToGroupParams struct {
	StudentID pgtype.UUID        `json:"student_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) error {
	_, err := q.db.Exec(ctx, addStudentToGroup, arg.StudentID, arg.GroupID, arg.JoinedAt)
	return err
}

const addStudentsToGroupBulk = `-- name: AddStudentsToGroupBulk :exec
INSERT INTO student_groups (student_id, group_id, joined_at)
SELECT student_id, $1, $3
FROM unnest($2::uuid[]) AS student_ids(student_id)
`

type AddStudentsToGroupBulkParams struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	Column2  []pgtype.UUID      `json:"column_2"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) AddStudentsToGroupBulk(ctx context.Context, arg AddStudentsToGroupBulkParams) error {
	_, err := q.db.Exec(ctx, addStudentsToGroupBulk, arg.GroupID, arg.Column2, arg.JoinedAt)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (branch_id, name, status)
VALUES ($1, $2, 'ACTIVE')
RETURNING id
`

type CreateGroupParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.BranchID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getGroupActiveStudentIDs = `-- name: GetGroupActiveStudentIDs :many
SELECT student_id
FROM student_groups
WHERE group_id = $1 AND left_at IS NULL
`

func (q *Queries) GetGroupActiveStudentIDs(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getGroupActiveStudentIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var student_id pgtype.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupBranchID = `-- name: GetGroupBranchID :one
SELECT branch_id FROM groups WHERE id = $1
`

func (q *Queries) GetGroupBranchID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGroupBranchID, id)
	var branch_id pgtype.UUID
	err := row.Scan(&branch_id)
	return branch_id, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, branch_id, name, status, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupStudents = `-- name: GetGroupStudents :many
SELECT s.id, s.first_name, s.last_name, s.phone, s.email, s.status
FROM students s
JOIN student_groups sg ON s.id = sg.student_id
WHERE sg.group_id = $1 AND sg.left_at IS NULL
ORDER BY s.last_name, s.first_name
`

type GetGroupStudentsRow struct {
	ID        pgtype.UUID      `json:"id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Phone     pgtype.Text      `json:"phone"`
	Email     pgtype.Text      `json:"email"`
	Status    NullEntityStatus `json:"status"`
}

func (q *Queries) GetGroupStudents(ctx context.Context, groupID pgtype.UUID) ([]GetGroupStudentsRow, error) {
	rows, err := q.db.Query(ctx, getGroupStudents, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupStudentsRow
	for rows.Next() {
		var i GetGroupStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByBranchID = `-- name: GetGroupsByBranchID :many
SELECT 
    g.id, 
    g.name, 
    g.status, 
    COALESCE(COUNT(sg.student_id), 0)::int as students_count
FROM groups g
LEFT JOIN student_groups sg ON g.id = sg.group_id AND sg.left_at IS NULL
WHERE g.branch_id = $1
    AND ($2::entity_status IS NULL OR g.status = $2::entity_status)
GROUP BY g.id, g.name, g.status
ORDER BY g.created_at DESC
`

type GetGroupsByBranchIDParams struct {
	BranchID pgtype.UUID      `json:"branch_id"`
	Status   NullEntityStatus `json:"status"`
}

type GetGroupsByBranchIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Status        NullEntityStatus `json:"status"`
	StudentsCount int32            `json:"students_count"`
}

func (q *Queries) GetGroupsByBranchID(ctx context.Context, arg GetGroupsByBranchIDParams) ([]GetGroupsByBranchIDRow, error) {
	rows, err := q.db.Query(ctx, getGroupsByBranchID, arg.BranchID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByBranchIDRow
	for rows.Next() {
		var i GetGroupsByBranchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.StudentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromGroup = `-- name: RemoveStudentFromGroup :exec
UPDATE student_groups
SET left_at = $3
WHERE student_id = $1 AND group_id = $2 AND left_at IS NULL
`

type RemoveStudentFromGroupParams struct {
	StudentID pgtype.UUID        `json:"student_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	LeftAt    pgtype.Timestamptz `json:"left_at"`
}

func (q *Queries) RemoveStudentFromGroup(ctx context.Context, arg RemoveStudentFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeStudentFromGroup, arg.StudentID, arg.GroupID, arg.LeftAt)
	return err
}

const removeStudentsFromGroupBulk = `-- name: RemoveStudentsFromGroupBulk :exec
UPDATE student_groups
SET left_at = $3
WHERE student_id = ANY($1::uuid[])
    AND group_id = $2
    AND left_at IS NULL
`

type RemoveStudentsFromGroupBulkParams struct {
	Column1 []pgtype.UUID      `json:"column_1"`
	GroupID pgtype.UUID        `json:"group_id"`
	LeftAt  pgtype.Timestamptz `json:"left_at"`
}

func (q *Queries) RemoveStudentsFromGroupBulk(ctx context.Context, arg RemoveStudentsFromGroupBulkParams) error {
	_, err := q.db.Exec(ctx, removeStudentsFromGroupBulk, arg.Column1, arg.GroupID, arg.LeftAt)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups
SET name = $1
WHERE id = $2
RETURNING id, branch_id, name, status, created_at
`

type UpdateGroupNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.Name, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateGroupStatus = `-- name: UpdateGroupStatus :exec
UPDATE groups
SET status = $1
WHERE id = $2
`

type UpdateGroupStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateGroupStatus(ctx context.Context, arg UpdateGroupStatusParams) error {
	_, err := q.db.Exec(ctx, updateGroupStatus, arg.Status, arg.ID)
	return err
}
