// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubjectsInBranch = `-- name: CountSubjectsInBranch :one
SELECT COUNT(*)::int
FROM unnest($2::uuid[]) AS subject_ids(id)
JOIN subjects s ON s.id = subject_ids.id
WHERE s.branch_id = $1
    AND s.status = 'ACTIVE'
`

type CountSubjectsInBranchParams struct {
	BranchID pgtype.UUID   `json:"branch_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

func (q *Queries) CountSubjectsInBranch(ctx context.Context, arg CountSubjectsInBranchParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSubjectsInBranch, arg.BranchID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPlanPricingGrid = `-- name: CreatePlanPricingGrid :exec
INSERT INTO plan_pricing_grid (plan_id, lessons_per_month, price_per_lesson)
VALUES ($1, $2, $3)
`

type CreatePlanPricingGridParams struct {
	PlanID          pgtype.UUID    `json:"plan_id"`
	LessonsPerMonth int32          `json:"lessons_per_month"`
	PricePerLesson  pgtype.Numeric `json:"price_per_lesson"`
}

func (q *Queries) CreatePlanPricingGrid(ctx context.Context, arg CreatePlanPricingGridParams) error {
	_, err := q.db.Exec(ctx, createPlanPricingGrid, arg.PlanID, arg.LessonsPerMonth, arg.PricePerLesson)
	return err
}

const createPlanSubject = `-- name: CreatePlanSubject :exec
INSERT INTO plan_subjects (plan_id, subject_id)
VALUES ($1, $2)
`

type CreatePlanSubjectParams struct {
	PlanID    pgtype.UUID `json:"plan_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

func (q *Queries) CreatePlanSubject(ctx context.Context, arg CreatePlanSubjectParams) error {
	_, err := q.db.Exec(ctx, createPlanSubject, arg.PlanID, arg.SubjectID)
	return err
}

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :one
INSERT INTO subscription_plans (branch_id, name, type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, branch_id, name, type, status, created_at
`

type CreateSubscriptionPlanParams struct {
	BranchID pgtype.UUID      `json:"branch_id"`
	Name     string           `json:"name"`
	Type     PlanType         `json:"type"`
	Status   NullEntityStatus `json:"status"`
}

func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPlan,
		arg.BranchID,
		arg.Name,
		arg.Type,
		arg.Status,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, branch_id, name, type, status, created_at
FROM subscription_plans
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanPricingGrids = `-- name: GetPlanPricingGrids :many
SELECT id, plan_id, lessons_per_month, price_per_lesson
FROM plan_pricing_grid
WHERE plan_id = $1
ORDER BY lessons_per_month ASC
`

func (q *Queries) GetPlanPricingGrids(ctx context.Context, planID pgtype.UUID) ([]PlanPricingGrid, error) {
	rows, err := q.db.Query(ctx, getPlanPricingGrids, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanPricingGrid
	for rows.Next() {
		var i PlanPricingGrid
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.LessonsPerMonth,
			&i.PricePerLesson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanSubjects = `-- name: GetPlanSubjects :many
SELECT s.id, s.name, s.description, s.status, s.created_at, s.updated_at
FROM subjects s
JOIN plan_subjects ps ON s.id = ps.subject_id
WHERE ps.plan_id = $1
`

type GetPlanSubjectsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      NullEntityStatus   `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlanSubjects(ctx context.Context, planID pgtype.UUID) ([]GetPlanSubjectsRow, error) {
	rows, err := q.db.Query(ctx, getPlanSubjects, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlanSubjectsRow
	for rows.Next() {
		var i GetPlanSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansByBranchID = `-- name: GetPlansByBranchID :many
SELECT id, branch_id, name, type, status, created_at
FROM subscription_plans
WHERE branch_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPlansByBranchID(ctx context.Context, branchID pgtype.UUID) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, getPlansByBranchID, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanStatus = `-- name: UpdatePlanStatus :exec
UPDATE subscription_plans
SET status = $2
WHERE id = $1
`

type UpdatePlanStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status NullEntityStatus `json:"status"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error {
	_, err := q.db.Exec(ctx, updatePlanStatus, arg.ID, arg.Status)
	return err
}

const validatePlanSubject = `-- name: ValidatePlanSubject :one
SELECT EXISTS (
    SELECT 1 
    FROM plan_subjects ps
    JOIN subscription_plans p ON p.id = ps.plan_id
    JOIN subjects s ON s.id = ps.subject_id
    WHERE ps.plan_id = $1
      AND ps.subject_id = $2
      AND p.status = 'ACTIVE'
      AND s.status = 'ACTIVE'
)
`

type ValidatePlanSubjectParams struct {
	PlanID    pgtype.UUID `json:"plan_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

func (q *Queries) ValidatePlanSubject(ctx context.Context, arg ValidatePlanSubjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, validatePlanSubject, arg.PlanID, arg.SubjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
