// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserToBranch(ctx context.Context, arg AssignUserToBranchParams) error
	CreateBranch(ctx context.Context, arg CreateBranchParams) (pgtype.UUID, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllBranches(ctx context.Context) ([]Branch, error)
	GetBranchByID(ctx context.Context, id pgtype.UUID) (Branch, error)
	GetBranchesByUserID(ctx context.Context, userID pgtype.UUID) ([]Branch, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserBranchIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) error
	UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) error
	UpdateSubjectStatus(ctx context.Context, arg UpdateSubjectStatusParams) error
}

var _ Querier = (*Queries)(nil)
