// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) error
	AddStudentsToGroupBulk(ctx context.Context, arg AddStudentsToGroupBulkParams) error
	AssignUserToBranch(ctx context.Context, arg AssignUserToBranchParams) error
	BulkCreateLessons(ctx context.Context, arg []BulkCreateLessonsParams) (int64, error)
	CancelFutureLessonsByTemplate(ctx context.Context, templateID pgtype.UUID) error
	CheckStudentConflict(ctx context.Context, arg CheckStudentConflictParams) (bool, error)
	CheckStudentConflictExcludingLesson(ctx context.Context, arg CheckStudentConflictExcludingLessonParams) (bool, error)
	CheckTeacherActiveTemplatesInBranch(ctx context.Context, arg CheckTeacherActiveTemplatesInBranchParams) (bool, error)
	CheckTeacherConflict(ctx context.Context, arg CheckTeacherConflictParams) (bool, error)
	CheckTeacherConflictExcludingLesson(ctx context.Context, arg CheckTeacherConflictExcludingLessonParams) (bool, error)
	CheckTeacherFutureLessonsInBranch(ctx context.Context, arg CheckTeacherFutureLessonsInBranchParams) (bool, error)
	CountActiveBranchesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) (int32, error)
	CountSubjectsInBranch(ctx context.Context, arg CountSubjectsInBranchParams) (int32, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (pgtype.UUID, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (pgtype.UUID, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreatePlanPricingGrid(ctx context.Context, arg CreatePlanPricingGridParams) error
	CreatePlanSubject(ctx context.Context, arg CreatePlanSubjectParams) error
	CreateStudent(ctx context.Context, arg CreateStudentParams) (pgtype.UUID, error)
	CreateStudentSubscription(ctx context.Context, arg CreateStudentSubscriptionParams) (StudentSubscription, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (LessonTemplate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateTemplate(ctx context.Context, id pgtype.UUID) error
	DeleteUserBranches(ctx context.Context, userID pgtype.UUID) error
	GetAdmins(ctx context.Context) ([]GetAdminsRow, error)
	GetAllBranches(ctx context.Context, status NullEntityStatus) ([]Branch, error)
	GetBranchByID(ctx context.Context, id pgtype.UUID) (Branch, error)
	GetBranchesByUserID(ctx context.Context, arg GetBranchesByUserIDParams) ([]Branch, error)
	GetGroupActiveStudentIDs(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error)
	GetGroupBranchID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupStudents(ctx context.Context, groupID pgtype.UUID) ([]GetGroupStudentsRow, error)
	GetGroupsByBranchID(ctx context.Context, arg GetGroupsByBranchIDParams) ([]GetGroupsByBranchIDRow, error)
	GetGroupsByBranchIDAndTeacherID(ctx context.Context, arg GetGroupsByBranchIDAndTeacherIDParams) ([]GetGroupsByBranchIDAndTeacherIDRow, error)
	GetLessonByID(ctx context.Context, id pgtype.UUID) (Lesson, error)
	GetPlanByID(ctx context.Context, id pgtype.UUID) (SubscriptionPlan, error)
	GetPlanPricingGrids(ctx context.Context, planID pgtype.UUID) ([]PlanPricingGrid, error)
	GetPlanSubjects(ctx context.Context, planID pgtype.UUID) ([]GetPlanSubjectsRow, error)
	GetPlansByBranchID(ctx context.Context, branchID pgtype.UUID) ([]SubscriptionPlan, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStudentBranchID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error)
	GetStudentSubscriptions(ctx context.Context, studentID pgtype.UUID) ([]GetStudentSubscriptionsRow, error)
	GetStudentsByBranchID(ctx context.Context, arg GetStudentsByBranchIDParams) ([]Student, error)
	GetStudentsByBranchIDAndTeacherID(ctx context.Context, arg GetStudentsByBranchIDAndTeacherIDParams) ([]Student, error)
	GetSubject(ctx context.Context, arg GetSubjectParams) (Subject, error)
	GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error)
	GetSubscriptionBranchIDs(ctx context.Context, arg GetSubscriptionBranchIDsParams) (GetSubscriptionBranchIDsRow, error)
	GetTeacherSchedule(ctx context.Context, arg GetTeacherScheduleParams) ([]Lesson, error)
	GetTeachers(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetTeachersRow, error)
	GetUserBranchIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserWithBranchesByID(ctx context.Context, id pgtype.UUID) ([]GetUserWithBranchesByIDRow, error)
	IsBranchActive(ctx context.Context, id pgtype.UUID) (bool, error)
	IsTeacherGroup(ctx context.Context, arg IsTeacherGroupParams) (bool, error)
	IsTeacherStudent(ctx context.Context, arg IsTeacherStudentParams) (pgtype.Bool, error)
	ListLessons(ctx context.Context, arg ListLessonsParams) ([]ListLessonsRow, error)
	ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]Subject, error)
	RemoveStudentFromGroup(ctx context.Context, arg RemoveStudentFromGroupParams) error
	RemoveStudentsFromGroupBulk(ctx context.Context, arg RemoveStudentsFromGroupBulkParams) error
	RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error)
	UpdateGroupStatus(ctx context.Context, arg UpdateGroupStatusParams) error
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error)
	UpdateLessonStatus(ctx context.Context, arg UpdateLessonStatusParams) error
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateStudentStatus(ctx context.Context, arg UpdateStudentStatusParams) error
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateSubjectStatus(ctx context.Context, arg UpdateSubjectStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (int64, error)
	ValidatePlanSubject(ctx context.Context, arg ValidatePlanSubjectParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
