// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveStudentsByBranch = `-- name: CountActiveStudentsByBranch :one
SELECT COUNT(id) 
FROM students 
WHERE branch_id = $1 
AND status = 'ACTIVE'
`

func (q *Queries) CountActiveStudentsByBranch(ctx context.Context, branchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStudentsByBranch, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCancelledLessonsByBranch = `-- name: CountCancelledLessonsByBranch :one
SELECT COUNT(id) 
FROM lessons 
WHERE branch_id = $1 
AND status = 'CANCELLED'
AND ($2::date IS NULL OR date >= $2::date)
AND ($3::date IS NULL OR date <= $3::date)
`

type CountCancelledLessonsByBranchParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CountCancelledLessonsByBranch(ctx context.Context, arg CountCancelledLessonsByBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCancelledLessonsByBranch, arg.BranchID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedLessonsByBranch = `-- name: CountCompletedLessonsByBranch :one
SELECT COUNT(id) 
FROM lessons 
WHERE branch_id = $1 
AND status = 'COMPLETED'
AND ($2::date IS NULL OR date >= $2::date)
AND ($3::date IS NULL OR date <= $3::date)
`

type CountCompletedLessonsByBranchParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CountCompletedLessonsByBranch(ctx context.Context, arg CountCompletedLessonsByBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedLessonsByBranch, arg.BranchID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBranchAttendanceStats = `-- name: GetBranchAttendanceStats :one
SELECT 
    COUNT(a.lesson_id)::bigint AS total_attendance_records,
    COUNT(a.lesson_id) FILTER (WHERE a.is_present)::bigint AS total_present_records
FROM attendance a
JOIN lessons l ON a.lesson_id = l.id
WHERE l.branch_id = $1
AND ($2::date IS NULL OR l.date >= $2::date)
AND ($3::date IS NULL OR l.date <= $3::date)
`

type GetBranchAttendanceStatsParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetBranchAttendanceStatsRow struct {
	TotalAttendanceRecords int64 `json:"total_attendance_records"`
	TotalPresentRecords    int64 `json:"total_present_records"`
}

func (q *Queries) GetBranchAttendanceStats(ctx context.Context, arg GetBranchAttendanceStatsParams) (GetBranchAttendanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getBranchAttendanceStats, arg.BranchID, arg.StartDate, arg.EndDate)
	var i GetBranchAttendanceStatsRow
	err := row.Scan(&i.TotalAttendanceRecords, &i.TotalPresentRecords)
	return i, err
}

const getStudentAttendanceHistory = `-- name: GetStudentAttendanceHistory :many
SELECT
    l.date,
    l.start_time,
    sub.name AS subject_name,
    COALESCE(a.is_present, false)::boolean AS is_present,
    COALESCE(a.notes, '')::text AS notes
FROM lessons l
JOIN subjects sub ON l.subject_id = sub.id
LEFT JOIN attendance a ON l.id = a.lesson_id AND a.student_id = $1
WHERE (l.student_id = $1 OR EXISTS (
    SELECT 1 FROM student_groups sg 
    WHERE sg.group_id = l.group_id 
    AND sg.student_id = $1
    AND sg.joined_at::date <= l.date
    AND (sg.left_at IS NULL OR sg.left_at::date > l.date)
))
AND l.status = 'COMPLETED'
AND ($2::date IS NULL OR l.date >= $2::date)
AND ($3::date IS NULL OR l.date <= $3::date)
AND ($4::uuid IS NULL OR l.subject_id = $4::uuid)
ORDER BY l.date DESC, l.start_time DESC
`

type GetStudentAttendanceHistoryParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

type GetStudentAttendanceHistoryRow struct {
	Date        time.Time `json:"date"`
	StartTime   time.Time `json:"start_time"`
	SubjectName string    `json:"subject_name"`
	IsPresent   bool      `json:"is_present"`
	Notes       string    `json:"notes"`
}

func (q *Queries) GetStudentAttendanceHistory(ctx context.Context, arg GetStudentAttendanceHistoryParams) ([]GetStudentAttendanceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getStudentAttendanceHistory,
		arg.StudentID,
		arg.StartDate,
		arg.EndDate,
		arg.SubjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentAttendanceHistoryRow
	for rows.Next() {
		var i GetStudentAttendanceHistoryRow
		if err := rows.Scan(
			&i.Date,
			&i.StartTime,
			&i.SubjectName,
			&i.IsPresent,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherStatistics = `-- name: GetTeacherStatistics :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'SCHEDULED')::int AS scheduled_lessons,
    COUNT(*) FILTER (WHERE status = 'COMPLETED')::int AS completed_lessons,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')::int AS cancelled_lessons
FROM lessons
WHERE teacher_id = $1
AND ($2::date IS NULL OR date >= $2::date)
AND ($3::date IS NULL OR date <= $3::date)
`

type GetTeacherStatisticsParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetTeacherStatisticsRow struct {
	ScheduledLessons int32 `json:"scheduled_lessons"`
	CompletedLessons int32 `json:"completed_lessons"`
	CancelledLessons int32 `json:"cancelled_lessons"`
}

func (q *Queries) GetTeacherStatistics(ctx context.Context, arg GetTeacherStatisticsParams) (GetTeacherStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getTeacherStatistics, arg.TeacherID, arg.StartDate, arg.EndDate)
	var i GetTeacherStatisticsRow
	err := row.Scan(&i.ScheduledLessons, &i.CompletedLessons, &i.CancelledLessons)
	return i, err
}
