// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateLessonsParams struct {
	BranchID   pgtype.UUID      `json:"branch_id"`
	TemplateID pgtype.UUID      `json:"template_id"`
	TeacherID  pgtype.UUID      `json:"teacher_id"`
	SubjectID  pgtype.UUID      `json:"subject_id"`
	StudentID  pgtype.UUID      `json:"student_id"`
	GroupID    pgtype.UUID      `json:"group_id"`
	Date       time.Time        `json:"date"`
	StartTime  time.Time        `json:"start_time"`
	EndTime    time.Time        `json:"end_time"`
	Status     NullLessonStatus `json:"status"`
}

const checkStudentConflict = `-- name: CheckStudentConflict :one
SELECT EXISTS (
    SELECT 1 FROM lessons l
    LEFT JOIN student_groups sg ON l.group_id = sg.group_id 
        AND sg.student_id = $1 
        AND sg.joined_at <= NOW() 
        AND (sg.left_at IS NULL OR sg.left_at > NOW())
    WHERE (l.student_id = $1 OR sg.student_id = $1)
      AND l.date = $2
      AND l.status != 'CANCELLED'
      AND l.start_time < $4
      AND l.end_time > $3
)
`

type CheckStudentConflictParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Date      time.Time   `json:"date"`
	EndTime   time.Time   `json:"end_time"`
	StartTime time.Time   `json:"start_time"`
}

func (q *Queries) CheckStudentConflict(ctx context.Context, arg CheckStudentConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkStudentConflict,
		arg.StudentID,
		arg.Date,
		arg.EndTime,
		arg.StartTime,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkTeacherConflict = `-- name: CheckTeacherConflict :one
SELECT EXISTS (
    SELECT 1 FROM lessons
    WHERE teacher_id = $1
      AND date = $2
      AND status != 'CANCELLED'
      AND start_time < $4
      AND end_time > $3
)
`

type CheckTeacherConflictParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	Date      time.Time   `json:"date"`
	EndTime   time.Time   `json:"end_time"`
	StartTime time.Time   `json:"start_time"`
}

func (q *Queries) CheckTeacherConflict(ctx context.Context, arg CheckTeacherConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTeacherConflict,
		arg.TeacherID,
		arg.Date,
		arg.EndTime,
		arg.StartTime,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (
    branch_id, template_id, teacher_id, subject_id, student_id, group_id, date, start_time, end_time, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, branch_id, template_id, teacher_id, subject_id, student_id, group_id, date, start_time, end_time, status, created_at
`

type CreateLessonParams struct {
	BranchID   pgtype.UUID      `json:"branch_id"`
	TemplateID pgtype.UUID      `json:"template_id"`
	TeacherID  pgtype.UUID      `json:"teacher_id"`
	SubjectID  pgtype.UUID      `json:"subject_id"`
	StudentID  pgtype.UUID      `json:"student_id"`
	GroupID    pgtype.UUID      `json:"group_id"`
	Date       time.Time        `json:"date"`
	StartTime  time.Time        `json:"start_time"`
	EndTime    time.Time        `json:"end_time"`
	Status     NullLessonStatus `json:"status"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.BranchID,
		arg.TemplateID,
		arg.TeacherID,
		arg.SubjectID,
		arg.StudentID,
		arg.GroupID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TemplateID,
		&i.TeacherID,
		&i.SubjectID,
		&i.StudentID,
		&i.GroupID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO lesson_templates (
    branch_id, teacher_id, subject_id, student_id, group_id, day_of_week, start_time, end_time, start_date, end_date, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, branch_id, teacher_id, subject_id, student_id, group_id, day_of_week, start_time, end_time, start_date, end_date, is_active
`

type CreateTemplateParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	StudentID pgtype.UUID `json:"student_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	DayOfWeek int32       `json:"day_of_week"`
	StartTime time.Time   `json:"start_time"`
	EndTime   time.Time   `json:"end_time"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	IsActive  pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (LessonTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.BranchID,
		arg.TeacherID,
		arg.SubjectID,
		arg.StudentID,
		arg.GroupID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
	)
	var i LessonTemplate
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TeacherID,
		&i.SubjectID,
		&i.StudentID,
		&i.GroupID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, branch_id, template_id, teacher_id, subject_id, student_id, group_id, date, start_time, end_time, status, created_at FROM lessons WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TemplateID,
		&i.TeacherID,
		&i.SubjectID,
		&i.StudentID,
		&i.GroupID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTeacherSchedule = `-- name: GetTeacherSchedule :many
SELECT id, branch_id, template_id, teacher_id, subject_id, student_id, group_id, date, start_time, end_time, status, created_at FROM lessons 
WHERE teacher_id = $1 
  AND date >= $2 
  AND date <= $3
ORDER BY date ASC, start_time ASC
`

type GetTeacherScheduleParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	Date      time.Time   `json:"date"`
	Date_2    time.Time   `json:"date_2"`
}

func (q *Queries) GetTeacherSchedule(ctx context.Context, arg GetTeacherScheduleParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, getTeacherSchedule, arg.TeacherID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.TemplateID,
			&i.TeacherID,
			&i.SubjectID,
			&i.StudentID,
			&i.GroupID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLessonStatus = `-- name: UpdateLessonStatus :exec
UPDATE lessons
SET status = $2
WHERE id = $1
`

type UpdateLessonStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status NullLessonStatus `json:"status"`
}

func (q *Queries) UpdateLessonStatus(ctx context.Context, arg UpdateLessonStatusParams) error {
	_, err := q.db.Exec(ctx, updateLessonStatus, arg.ID, arg.Status)
	return err
}
