// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    branch_id, first_name, last_name, dob, phone, email, address,
    parent_name, parent_phone, parent_email, parent_relationship, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'ACTIVE'
) RETURNING id
`

type CreateStudentParams struct {
	BranchID           pgtype.UUID `json:"branch_id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	Dob                pgtype.Date `json:"dob"`
	Phone              pgtype.Text `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	ParentName         string      `json:"parent_name"`
	ParentPhone        string      `json:"parent_phone"`
	ParentEmail        pgtype.Text `json:"parent_email"`
	ParentRelationship pgtype.Text `json:"parent_relationship"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.BranchID,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.ParentEmail,
		arg.ParentRelationship,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getStudentBranchID = `-- name: GetStudentBranchID :one
SELECT branch_id FROM students WHERE id = $1
`

func (q *Queries) GetStudentBranchID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getStudentBranchID, id)
	var branch_id pgtype.UUID
	err := row.Scan(&branch_id)
	return branch_id, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, branch_id, first_name, last_name, dob, phone, email, address, parent_name, parent_phone, parent_email, parent_relationship, status, created_at
FROM students 
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentsByBranchID = `-- name: GetStudentsByBranchID :many
SELECT id, branch_id, first_name, last_name, dob, phone, email, address, parent_name, parent_phone, parent_email, parent_relationship, status, created_at
FROM students
WHERE branch_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetStudentsByBranchID(ctx context.Context, branchID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsByBranchID, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Dob,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.ParentName,
			&i.ParentPhone,
			&i.ParentEmail,
			&i.ParentRelationship,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :exec
UPDATE students
SET first_name = $1, last_name = $2, dob = $3, phone = $4, email = $5,
    address = $6, parent_name = $7, parent_phone = $8, parent_email = $9,
    parent_relationship = $10
WHERE id = $11
`

type UpdateStudentParams struct {
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	Dob                pgtype.Date `json:"dob"`
	Phone              pgtype.Text `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	ParentName         string      `json:"parent_name"`
	ParentPhone        string      `json:"parent_phone"`
	ParentEmail        pgtype.Text `json:"parent_email"`
	ParentRelationship pgtype.Text `json:"parent_relationship"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) error {
	_, err := q.db.Exec(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.ParentEmail,
		arg.ParentRelationship,
		arg.ID,
	)
	return err
}

const updateStudentStatus = `-- name: UpdateStudentStatus :exec
UPDATE students
SET status = $1
WHERE id = $2
`

type UpdateStudentStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateStudentStatus(ctx context.Context, arg UpdateStudentStatusParams) error {
	_, err := q.db.Exec(ctx, updateStudentStatus, arg.Status, arg.ID)
	return err
}
