// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    branch_id, first_name, last_name, dob, phone, email, address,
    parent_name, parent_phone, parent_email, parent_relationship, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'ACTIVE'
) RETURNING id
`

type CreateStudentParams struct {
	BranchID           pgtype.UUID `json:"branch_id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	Dob                pgtype.Date `json:"dob"`
	Phone              pgtype.Text `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	ParentName         string      `json:"parent_name"`
	ParentPhone        string      `json:"parent_phone"`
	ParentEmail        pgtype.Text `json:"parent_email"`
	ParentRelationship pgtype.Text `json:"parent_relationship"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.BranchID,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.ParentEmail,
		arg.ParentRelationship,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getStudentBranchID = `-- name: GetStudentBranchID :one
SELECT branch_id FROM students WHERE id = $1
`

func (q *Queries) GetStudentBranchID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getStudentBranchID, id)
	var branch_id pgtype.UUID
	err := row.Scan(&branch_id)
	return branch_id, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, branch_id, first_name, last_name, dob, phone, email, address, parent_name, parent_phone, parent_email, parent_relationship, status, created_at
FROM students 
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentsByBranchID = `-- name: GetStudentsByBranchID :many
SELECT id, branch_id, first_name, last_name, dob, phone, email, address, parent_name, parent_phone, parent_email, parent_relationship, status, created_at
FROM students
WHERE branch_id = $1
    AND ($2::entity_status IS NULL OR status = $2::entity_status)
ORDER BY created_at DESC
`

type GetStudentsByBranchIDParams struct {
	BranchID pgtype.UUID      `json:"branch_id"`
	Status   NullEntityStatus `json:"status"`
}

func (q *Queries) GetStudentsByBranchID(ctx context.Context, arg GetStudentsByBranchIDParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsByBranchID, arg.BranchID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Dob,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.ParentName,
			&i.ParentPhone,
			&i.ParentEmail,
			&i.ParentRelationship,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsByBranchIDAndTeacherID = `-- name: GetStudentsByBranchIDAndTeacherID :many
SELECT DISTINCT s.id, s.branch_id, s.first_name, s.last_name, s.dob, s.phone, s.email, s.address, s.parent_name, s.parent_phone, s.parent_email, s.parent_relationship, s.status, s.created_at
FROM students s
WHERE s.branch_id = $1
    AND ($3::entity_status IS NULL OR s.status = $3::entity_status)
    AND (
        EXISTS (
            SELECT 1
            FROM lessons l
            WHERE l.teacher_id = $2 AND l.student_id = s.id
        )
        OR EXISTS (
            SELECT 1
            FROM lessons l
            JOIN student_groups sg ON sg.group_id = l.group_id AND sg.left_at IS NULL
            WHERE l.teacher_id = $2 AND sg.student_id = s.id
        )
    )
ORDER BY s.created_at DESC
`

type GetStudentsByBranchIDAndTeacherIDParams struct {
	BranchID  pgtype.UUID      `json:"branch_id"`
	TeacherID pgtype.UUID      `json:"teacher_id"`
	Status    NullEntityStatus `json:"status"`
}

func (q *Queries) GetStudentsByBranchIDAndTeacherID(ctx context.Context, arg GetStudentsByBranchIDAndTeacherIDParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsByBranchIDAndTeacherID, arg.BranchID, arg.TeacherID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.FirstName,
			&i.LastName,
			&i.Dob,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.ParentName,
			&i.ParentPhone,
			&i.ParentEmail,
			&i.ParentRelationship,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeacherStudent = `-- name: IsTeacherStudent :one
SELECT (
    EXISTS (
        SELECT 1
        FROM lessons l
        WHERE l.teacher_id = $1 AND l.student_id = $2
    )
    OR EXISTS (
        SELECT 1
        FROM lessons l
        JOIN student_groups sg ON sg.group_id = l.group_id AND sg.left_at IS NULL
        WHERE l.teacher_id = $1 AND sg.student_id = $2
    )
) AS is_teacher_student
`

type IsTeacherStudentParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) IsTeacherStudent(ctx context.Context, arg IsTeacherStudentParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isTeacherStudent, arg.TeacherID, arg.StudentID)
	var is_teacher_student pgtype.Bool
	err := row.Scan(&is_teacher_student)
	return is_teacher_student, err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET first_name = $1, last_name = $2, dob = $3, phone = $4, email = $5,
    address = $6, parent_name = $7, parent_phone = $8, parent_email = $9,
    parent_relationship = $10
WHERE id = $11 RETURNING id, branch_id, first_name, last_name, dob, phone, email, address, parent_name, parent_phone, parent_email, parent_relationship, status, created_at
`

type UpdateStudentParams struct {
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	Dob                pgtype.Date `json:"dob"`
	Phone              pgtype.Text `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	ParentName         string      `json:"parent_name"`
	ParentPhone        string      `json:"parent_phone"`
	ParentEmail        pgtype.Text `json:"parent_email"`
	ParentRelationship pgtype.Text `json:"parent_relationship"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.ParentEmail,
		arg.ParentRelationship,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.ParentEmail,
		&i.ParentRelationship,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateStudentStatus = `-- name: UpdateStudentStatus :exec
UPDATE students
SET status = $1
WHERE id = $2
`

type UpdateStudentStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateStudentStatus(ctx context.Context, arg UpdateStudentStatusParams) error {
	_, err := q.db.Exec(ctx, updateStudentStatus, arg.Status, arg.ID)
	return err
}
