// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (branch_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, branch_id, name, description, status, created_at, updated_at
`

type CreateSubjectParams struct {
	BranchID    pgtype.UUID `json:"branch_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.BranchID, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubject = `-- name: GetSubject :one
SELECT id, branch_id, name, description, status, created_at, updated_at
FROM subjects
WHERE id = $1 AND branch_id = $2
LIMIT 1
`

type GetSubjectParams struct {
	ID       pgtype.UUID `json:"id"`
	BranchID pgtype.UUID `json:"branch_id"`
}

func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, arg.ID, arg.BranchID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, branch_id, name, description, status, created_at, updated_at
FROM subjects
WHERE branch_id = $1
ORDER BY name ASC
`

func (q *Queries) ListSubjects(ctx context.Context, branchID pgtype.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET branch_id = $1, name = $2, description = $3, updated_at = NOW()
WHERE id = $4 RETURNING id, branch_id, name, description, status, created_at, updated_at
`

type UpdateSubjectParams struct {
	BranchID    pgtype.UUID `json:"branch_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.BranchID,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubjectStatus = `-- name: UpdateSubjectStatus :exec
UPDATE subjects
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateSubjectStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateSubjectStatus(ctx context.Context, arg UpdateSubjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubjectStatus, arg.Status, arg.ID)
	return err
}
