// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name, description)
VALUES ($1, $2)
RETURNING id
`

type CreateSubjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Name, arg.Description)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateSubjectStatus = `-- name: UpdateSubjectStatus :exec
UPDATE subjects
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateSubjectStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateSubjectStatus(ctx context.Context, arg UpdateSubjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubjectStatus, arg.Status, arg.ID)
	return err
}
