// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name, description)
VALUES ($1, $2)
RETURNING id
`

type CreateSubjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Name, arg.Description)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllSubjects = `-- name: GetAllSubjects :many
SELECT id, name, description, status, created_at, updated_at
FROM subjects
ORDER BY name ASC
`

func (q *Queries) GetAllSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, getAllSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :exec
UPDATE subjects
SET name = $1, description = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateSubjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) error {
	_, err := q.db.Exec(ctx, updateSubject, arg.Name, arg.Description, arg.ID)
	return err
}

const updateSubjectStatus = `-- name: UpdateSubjectStatus :exec
UPDATE subjects
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateSubjectStatusParams struct {
	Status NullEntityStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateSubjectStatus(ctx context.Context, arg UpdateSubjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubjectStatus, arg.Status, arg.ID)
	return err
}
