// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudentSubscription = `-- name: CreateStudentSubscription :one
INSERT INTO student_subscriptions (student_id, plan_id, subject_id, start_date)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, plan_id, subject_id, start_date, created_at
`

type CreateStudentSubscriptionParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	PlanID    pgtype.UUID `json:"plan_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) CreateStudentSubscription(ctx context.Context, arg CreateStudentSubscriptionParams) (StudentSubscription, error) {
	row := q.db.QueryRow(ctx, createStudentSubscription,
		arg.StudentID,
		arg.PlanID,
		arg.SubjectID,
		arg.StartDate,
	)
	var i StudentSubscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.PlanID,
		&i.SubjectID,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentSubscriptions = `-- name: GetStudentSubscriptions :many
SELECT 
    ss.id, 
    ss.student_id,
    ss.plan_id,
    ss.subject_id,
    ss.start_date,
    ss.created_at,
    p.name AS plan_name,
    s.name AS subject_name
FROM student_subscriptions ss
JOIN subscription_plans p ON ss.plan_id = p.id
JOIN subjects s ON ss.subject_id = s.id
WHERE ss.student_id = $1
ORDER BY ss.start_date DESC
`

type GetStudentSubscriptionsRow struct {
	ID          pgtype.UUID        `json:"id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	StartDate   pgtype.Date        `json:"start_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PlanName    string             `json:"plan_name"`
	SubjectName string             `json:"subject_name"`
}

func (q *Queries) GetStudentSubscriptions(ctx context.Context, studentID pgtype.UUID) ([]GetStudentSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getStudentSubscriptions, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentSubscriptionsRow
	for rows.Next() {
		var i GetStudentSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.SubjectID,
			&i.StartDate,
			&i.CreatedAt,
			&i.PlanName,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionBranchIDs = `-- name: GetSubscriptionBranchIDs :one
SELECT st.branch_id AS student_branch_id,
       p.branch_id AS plan_branch_id,
       s.branch_id AS subject_branch_id
FROM students st
JOIN subscription_plans p ON p.id = $2
JOIN subjects s ON s.id = $3
WHERE st.id = $1
LIMIT 1
`

type GetSubscriptionBranchIDsParams struct {
	ID   pgtype.UUID `json:"id"`
	ID_2 pgtype.UUID `json:"id_2"`
	ID_3 pgtype.UUID `json:"id_3"`
}

type GetSubscriptionBranchIDsRow struct {
	StudentBranchID pgtype.UUID `json:"student_branch_id"`
	PlanBranchID    pgtype.UUID `json:"plan_branch_id"`
	SubjectBranchID pgtype.UUID `json:"subject_branch_id"`
}

func (q *Queries) GetSubscriptionBranchIDs(ctx context.Context, arg GetSubscriptionBranchIDsParams) (GetSubscriptionBranchIDsRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionBranchIDs, arg.ID, arg.ID_2, arg.ID_3)
	var i GetSubscriptionBranchIDsRow
	err := row.Scan(&i.StudentBranchID, &i.PlanBranchID, &i.SubjectBranchID)
	return i, err
}
