// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToBranch = `-- name: AssignUserToBranch :exec
INSERT INTO user_branches (user_id, branch_id)
VALUES ($1, $2)
`

type AssignUserToBranchParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	BranchID pgtype.UUID `json:"branch_id"`
}

func (q *Queries) AssignUserToBranch(ctx context.Context, arg AssignUserToBranchParams) error {
	_, err := q.db.Exec(ctx, assignUserToBranch, arg.UserID, arg.BranchID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, password_hash, first_name, last_name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, phone, password_hash, first_name, last_name, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Phone        string   `json:"phone"`
	PasswordHash string   `json:"password_hash"`
	FirstName    string   `json:"first_name"`
	LastName     string   `json:"last_name"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBranchIDs = `-- name: GetUserBranchIDs :many
SELECT branch_id
FROM user_branches
WHERE user_id = $1
`

func (q *Queries) GetUserBranchIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserBranchIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var branch_id pgtype.UUID
		if err := rows.Scan(&branch_id); err != nil {
			return nil, err
		}
		items = append(items, branch_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, first_name, last_name, role, is_active, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, first_name, last_name, role, is_active, created_at, updated_at
FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
