env: "local"

http_server:
  address: ":8080"
  read_timeout: 5s
  write_timeout: 10s

postgres:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  db_name: "app"
  sslmode: "disable"  