name: Backend CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.7'
        cache: true

    - name: Create dummy .env
      run: touch .env

    - name: Download Go modules
      run: go mod download
    
    - name: Install Swagger CLI
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v9.2.0
      with:
        version: v2.11.4 
        install-mode: binary

    - name: Run Unit Tests
      run: make test

    - name: Verify Build
      run: make build